application: 5lide-editor
version: new
runtime: python27
threadsafe: true
api_version: 1

libraries:
- name: jinja2
  version: "2.6"

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /src
  static_dir: src

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: .*
  script: slides.app
