application: 5lide-viewer
version: new
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /deckjs/
  static_files: deckjs/index.html
  upload: deckjs/index.html

- url: /deckjs
  static_dir: deckjs

- url: /fathomjs/
  static_files: fathomjs/index.html
  upload: fathomjs/index.html

- url: /fathomjs
  static_dir: fathomjs

- url: /common
  static_dir: common